export enum BATCH_UPDATE {
    PARSE_TABLE_REQUEST = 'BATCH_UPDATE_PARSE_TABLE_REQUEST',
    PARSE_TABLE_OK = 'BATCH_UPDATE_PARSE_TABLE_OK',
    PARSE_TABLE_ERROR = 'BATCH_UPDATE_PARSE_TABLE_ERROR',
}
