export enum TASKS {
    FETCH_ALL_COURSE_RELATED = 'TASKS_FETCH_ALL_COURSE_RELATED',
    FETCH_ALL_COURSE_RELATED_OK = 'TASKS_FETCH_ALL_COURSE_RELATED_OK',
    FETCH_ALL_COURSE_RELATED_FAIL = 'TASKS_FETCH_ALL_COURSE_RELATED_FAIL',
}
